from decimal import Decimal
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator

from .validation import validate_transaction_type, validate_is_number
from moneytrack.core.constants import TransactionType
from moneytrack.core.models import TimeStampedModel

class Transaction(TimeStampedModel):
    # The 'id' field is automatically generated by Django behind the scenes as a BigAutoField!
    
    category = models.ForeignKey(
        'Category', 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True,
        related_name='transactions'
    )
    
    description = models.CharField(max_length=255, blank=True)
        
    amount = models.DecimalField(
        db_column='amount',
        verbose_name='Nominal',
        max_digits=12,
        decimal_places=2,
        default=Decimal('0.00'),
        validators=[MinValueValidator(Decimal('0.00'))],
    )
    
    user = models.CharField(max_length=255, verbose_name='User', blank=True)
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Transaction'
        verbose_name_plural = 'Transactions'
        indexes = [
            models.Index(fields=['-created_at']),
        ]

    def __str__(self):
        return (
            f'Transaction {self.pk} on {self.created_at:%Y-%m-%d} '
            f'— amount: {self.amount}'
        )
        
class Category(TimeStampedModel):
    name = models.CharField(max_length=100, verbose_name="Category Name", unique=True)
    # Soft Delete Field
    is_active = models.BooleanField(default=True, verbose_name="Is Active")

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        

    def __str__(self):
        return f"{self.name} is created on {self.created_at:%Y-%m-%d %H:%M:%S}"