# Generated by Django 4.1.7 on 2026-06-20 05:19

from django.db import migrations, models
import django.utils.timezone
import moneytrace.validation
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('transactionDate', models.DateTimeField(db_column='transaction_date', default=django.utils.timezone.now, unique=True, verbose_name='Transaction Date')),
                ('transactionType', models.CharField(choices=[('D', 'Debit'), ('C', 'Credit')], max_length=1, validators=[moneytrace.validation.validate_transaction_type], verbose_name='transaction_type')),
                ('valueDebet', models.FloatField(db_column='value_debet', default=0, validators=[moneytrace.validation.validate_is_number], verbose_name='Value Debet')),
                ('valueCredit', models.FloatField(db_column='value_credit', default=0, validators=[moneytrace.validation.validate_is_number], verbose_name='Value Credit')),
                ('sum_value', models.FloatField(db_column='sum_value', default=0, validators=[moneytrace.validation.validate_is_number], verbose_name='Sum Value')),
            ],
        ),
    ]
