# Generated by Django 4.1.7 on 2023-03-25 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        default=uuid.uuid5,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "transactionDate",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_column="transaction_date",
                        unique=True,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "transactionType",
                    models.CharField(
                        choices=[("D", "Debit"), ("C", "Credit")],
                        max_length=1,
                        verbose_name="transaction_type",
                    ),
                ),
                (
                    "valueDebet",
                    models.BigIntegerField(
                        db_column="value_debet", default=0, verbose_name="Value Debet"
                    ),
                ),
                (
                    "valueCredit",
                    models.BigIntegerField(
                        db_column="value_credit", default=0, verbose_name="Value Credit"
                    ),
                ),
            ],
        ),
    ]
