# Generated by Django 5.2.15 on 2026-06-21 06:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import moneytrace.validation
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category_type', models.TextField(max_length=62, verbose_name='Category Type')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('icon', models.CharField(blank=True, help_text="e.g., 'fas-fa-shopping-cart'", max_length=50)),
                ('color', models.CharField(default='#FFFFFF', help_text='Hex code (e.g., #FF5733)', max_length=7)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'unique_together': {('name', 'category_type')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('transaction_date', models.DateTimeField(db_column='transaction_date', default=django.utils.timezone.now, verbose_name='Transaction Date')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], default='EXPENSE', max_length=10, validators=[moneytrace.validation.validate_transaction_type], verbose_name='Transaction Type')),
                ('value_debet', models.DecimalField(db_column='value_debet', decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[moneytrace.validation.validate_is_number, django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Value Debit')),
                ('value_credit', models.DecimalField(db_column='value_credit', decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[moneytrace.validation.validate_is_number, django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Value Credit')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='moneytrace.category')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['-transaction_date'], name='moneytrace__transac_338689_idx')],
            },
        ),
    ]
