# Generated by Django 5.2.15 on 2026-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytrace', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Category Name'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
    ]
