# Generated by Django 4.1.7 on 2023-03-25 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("moneytrace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="sum_value",
            field=models.BigIntegerField(
                db_column="sum_value", default=0, verbose_name="Sum Value"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
