# Generated by Django 5.2.15 on 2026-06-21 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneytrace', '0002_alter_category_unique_together_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
