# Generated by Django 4.1.5 on 2023-04-01 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("moneytrace", "0002_transaction_sum_value_alter_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                auto_created=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transactionDate",
            field=models.DateTimeField(
                db_column="transaction_date",
                default=django.utils.timezone.now,
                unique=True,
                verbose_name="Transaction Date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("id",)},
        ),
    ]
