# Generated by Django 4.1.5 on 2023-04-01 11:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("moneytrace", "0003_alter_transaction_id_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.UUIDField(
                auto_created=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
