# Generated by Django 5.2.15 on 2026-06-21 07:10

import django.core.validators
import moneytrace.validation
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytrace', '0003_remove_category_color_remove_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='value_credit',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value_debet',
        ),
        migrations.AddField(
            model_name='transaction',
            name='amoun',
            field=models.DecimalField(db_column='amount', decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[moneytrace.validation.validate_is_number, django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Nominal'),
        ),
    ]
