# Generated by Django 4.1.5 on 2023-04-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneytrace", "0004_alter_transaction_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="sum_value",
            field=models.FloatField(
                db_column="sum_value", default=0, verbose_name="Sum Value"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="valueCredit",
            field=models.FloatField(
                db_column="value_credit", default=0, verbose_name="Value Credit"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="valueDebet",
            field=models.FloatField(
                db_column="value_debet", default=0, verbose_name="Value Debet"
            ),
        ),
    ]
