# Generated by Django 5.2.15 on 2026-06-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneytrace', '0004_remove_transaction_value_credit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amoun',
            new_name='amount',
        ),
    ]
