# Generated by Django 4.1.7 on 2023-04-16 19:26

from django.db import migrations, models
import moneytrace.validation


class Migration(migrations.Migration):
    dependencies = [
        ("moneytrace", "0005_alter_transaction_sum_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="sum_value",
            field=models.FloatField(
                db_column="sum_value",
                default=0,
                validators=[moneytrace.validation.validate_is_number],
                verbose_name="Sum Value",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transactionType",
            field=models.CharField(
                choices=[("D", "Debit"), ("C", "Credit")],
                max_length=1,
                validators=[moneytrace.validation.validate_transaction_type],
                verbose_name="transaction_type",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="valueCredit",
            field=models.FloatField(
                db_column="value_credit",
                default=0,
                validators=[moneytrace.validation.validate_is_number],
                verbose_name="Value Credit",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="valueDebet",
            field=models.FloatField(
                db_column="value_debet",
                default=0,
                validators=[moneytrace.validation.validate_is_number],
                verbose_name="Value Debet",
            ),
        ),
    ]
