# Generated by Django 4.1.7 on 2023-05-06 16:06

from django.db import migrations, models
import moneytrace.validation


class Migration(migrations.Migration):
    dependencies = [
        ("moneytrace", "0005_alter_transaction_sum_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transactionType",
            field=models.CharField(
                choices=[("D", "Debit"), ("C", "Credit")],
                max_length=1,
                validators=[moneytrace.validation.validate_transaction_type],
                verbose_name="transaction_type",
            ),
        ),
    ]
