# Generated by Django 4.1.7 on 2024-03-23 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moneytrace", "0006_alter_transaction_sum_value_and_more"),
        ("moneytrace", "0006_alter_transaction_transactiontype"),
    ]

    operations = []
