# Generated by Django 5.2.15 on 2026-08-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneytrace', '0009_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.CharField(blank=True, max_length=255, verbose_name='User'),
        ),
    ]
